services:
  web:
    build:  # Собираем образ из Dockerfile в текущей директории
      context: .
      dockerfile: Dockerfile
    image: customer-api-v1  # Локальное имя образа для web сервиса
    ports:
      - "5000:5000"  # Порт для доступа к Flask API
    environment:
      - DATABASE_URL=postgresql://postgres:Gl00m88@db/postgres  # Подключение к Postgres через имя сервиса `db`
      - BASE_URL=http://192.168.88.18:5000/api/v1/customers  # Устанавливаем BASE_URL для тестов
    depends_on:
      - db  # Убедимся, что база данных стартует до `web`
    restart: no

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Gl00m88
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Хранение данных Postgres
    ports:
      - "5432:5432"  # Порт для подключения к базе данных
    restart: always

volumes:
  postgres_data:

# Определение пользовательской сети (опционально, если хотите вручную создать сеть)
networks:
  default:
    driver: bridge
