services:
  # Auth Service
  auth_service:
    build:
      context: /home/dgornostaev/flask-auth-jwt
      dockerfile: Dockerfile
    image: auth-service
    environment:
      - AUTH_DATABASE_URL
      - SECRET_KEY
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: always
    networks:
      - backend_network

  # Flask API Service
  web:
    build:
      context: /home/dgornostaev/flask-rest-api-v1
      dockerfile: Dockerfile
    image: customer-api-v1
    environment:
      - BASE_URL
      - CUSTOMERS_DATABASE_URL
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    networks:
      - backend_network

  # Postgres Database
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Gl00m88
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
