services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart:
      always


  db:
    image: postgres  # Use the official Postgres Image
    environment:
      POSTGRES_USER: postgres # DB User
      POSTGRES_PASSWORD: Gl00m88  # DB Password
      POSTGRES_DB: postgres  # Our Postgres Database
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Create volume for DB Storage
    ports:
      - "5432:5432"  # Forward ports if you need to connect from the outside
    restart:
      always

volumes:
  postgres_data:  # Defining a volume for storing Postgres data