services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    env_file: .env  # Указываем путь к файлу .env

  db:
    image: postgres  # Официальный образ Postgres
    environment:
      POSTGRES_USER: postgres  # Пользователь базы данных
      POSTGRES_PASSWORD: Gl00m88  # Пароль базы данных
      POSTGRES_DB: postgres  # Имя базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Создание тома для хранения данных БД
    ports:
      - "5432:5432"  # Проброс порта для подключения снаружи
    restart: always

volumes:
  postgres_data:  # Определение тома для хранения данных Postgres
