services:
  web:
    image: customer-api-v1
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:Gl00m88@192.168.88.18/postgres  # Продуктивная БД
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gl00m88
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:

