services:
  web:
    image: customer-api-v1  # Using Flask Application Image
    ports:
      - "5000:5000"  # Port forwarding for Flask API
    environment:
      - DATABASE_URL  # Postgres Connection Url
      - BASE_URL  # from .env file
    depends_on:
      - db  # The container with Postgres starts earlier
    restart:
      always

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Gl00m88
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:

