services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BASE_URL=${BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13  # Укажите подходящую версию Postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gl00m88
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
