services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer-api-v1
    ports:
      - "5000:5000"

    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Gl00m88
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: no

volumes:
  postgres_data:


networks:
  default:
    driver: bridge
