name: Deploy to Raspberry Pi 3B

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Raspberry Pi 3B
        run: |
          ssh -p 8022 -o StrictHostKeyChecking=no dgornostaev@178.218.58.175 << 'EOF'
            cd /home/dgornostaev/flask-rest-api-v1

            # Pull the latest changes
            git pull origin main --no-rebase

            # Build and start the production containers
            docker compose up -d --build

            # Wait for services to initialize
            echo "Waiting for services to start..."
            sleep 20

            # Now let's run pytest in the web container on the production database
            echo "Running tests on production database..."
            docker compose exec web /usr/local/bin/pytest --maxfail=5 --disable-warnings --verbose || echo "Tests failed"

            # Optionally check the logs for debugging
            docker compose logs web
          EOF
