name: Deploy to Raspberry Pi 3B

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step to build and run the application with the test database
      - name: Deploy and test on Raspberry Pi 3B
        run: |
          ssh -p 8022 -o StrictHostKeyChecking=no dgornostaev@178.218.58.175 << 'EOF'
            cd /home/dgornostaev/flask-rest-api-v1

            # Явное указание merge стратегии при pull
            git pull origin main --no-rebase

            docker compose up -d test_db web

            sleep 10  # Allow time for DB initialization

            docker compose exec test_db psql -U test_user -d test_db -c "CREATE TABLE IF NOT EXISTS customers (customer_id SERIAL PRIMARY KEY, name VARCHAR(100), address VARCHAR(255));"

            docker compose exec web pytest tests/ --maxfail=5 --disable-warnings

            docker compose down --volumes --remove-orphans

            docker compose up -d --build
          EOF