name: Deploy Application

# Блок on, определяющий, при каких событиях запускается workflow
on:
  push:
    branches:
      - main  # Запуск при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Обновлено

      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.3  # Альтернатива для webfactory/ssh-agent
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 8022

      - name: Deploy to server
        run: |
          ssh -p 8022 dgornostaev@178.218.58.175 "cd /home/dgornostaev/flask-rest-api-v1 && docker-compose pull && docker-compose up -d"

