name: Test and Deploy on Raspberry PI 3B (Docker-host)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and Test on Raspberry Pi
        run: |
          ssh -p 8022 -o StrictHostKeyChecking=no dgornostaev@178.218.58.175 << 'EOF'
            # Go to the first project directory and pull the code
            cd /home/dgornostaev/flask-rest-api-v1
            git pull origin main
            
            # Go to the first project directory and pull the code
            cd /home/dgornostaev/flask-auth-jwt
            git pull origin main
            
            # Rebuild and restart containers using docker-compose.yml
            echo "Building and recreating Docker containers with updated code..."
            cd /home/dgornostaev/flask-rest-api-v1
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d --build --force-recreate
            
            # Wait for containers to be ready
            echo "Waiting for containers to be fully operational..."
            sleep 10

            # Run tests inside web docker container
            echo "Running tests inside the Flask Auth Service container and REST API container..."
            docker compose -f docker-compose.yml exec auth_service pytest tests --verbose --disable-warnings && docker compose -f docker-compose.yml exec web pytest tests --verbose --disable-warnings  || (echo "Tests auth failed!" && exit 1)
            echo "Running tests inside the Flask application container..."
            || (echo "Tests failed!" && exit 1)
            
            echo "Deployment and testing completed on Raspberry Pi 3B."
          EOF