name: Test and Deploy on Raspberry PI 3B

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key:
      - name: Copy .env to Raspberry Pi
        run: |
          scp -P 8022 -o StrictHostKeyChecking=no .env dgornostaev@178.218.58.175:/home/dgornostaev/flask-rest-api-v1/.env
      - name: Verify .env on Raspberry Pi
        run: |
          ssh -p 8022 -o StrictHostKeyChecking=no dgornostaev@178.218.58.175 'ls /home/dgornostaev/flask-rest-api-v1/.env'
      

      - name: Deploy and Test on Raspberry Pi
        run: |
          ssh -p 8022 -o StrictHostKeyChecking=no dgornostaev@178.218.58.175 << 'EOF'
            cd /home/dgornostaev/flask-rest-api-v1

            echo "Pulling latest changes and building Docker containers..."
            docker compose down
            docker compose up -d --build

            echo "Waiting for containers to be fully operational..."
            sleep 10  # Увеличьте время ожидания, если база данных поднимается дольше

            echo "Checking if Flask application container is running..."
            docker ps | grep web || (echo "Flask container failed to start!" && exit 1)

            echo "Running tests inside the Flask application container..."
            docker exec web pytest tests --verbose --disable-warnings || (echo "Tests failed!" && exit 1)

            echo "Tests completed successfully!"
          EOF

