name: Deploy Flask Application on Raspberry PI 3B

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Обновлено

      - name: Setup SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 178.218.58.175  # Укажи свой хост здесь
          username: dgornostaev  # Укажи пользователя здесь
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 8022  # Порт указываем только здесь

      - name: Deploy to server
        run: |
          ssh dgornostaev@178.218.58.175 "cd /home/dgornostaev/flask-rest-api-v1 && docker-compose pull && docker-compose up -d"
